versions:
  "1.3.1":
    folder: "1.x.x"
  "1.3.0":
    folder: "1.x.x"
  "1.2.0":
    folder: "1.x.x"
  "1.1.0":
    folder: "1.x.x"
  "1.0.1":
    folder: "1.x.x"
  "1.0.0":
    folder: "1.x.x"
  "0.1.14":
    folder: "0.x.x"
  "0.1.13":
    folder: "0.x.x"
  "0.1.12":
    folder: "0.x.x"
  "0.1.7":
    folder: "0.x.x"
  "0.1.6":
    folder: "0.x.x"
  "0.1.5":
    folder: "0.x.x"
